// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6VaTmnfKvM5eRWDkG4siqpCA7AFCQLVY',
    appId: '1:889730267326:web:77a1d054ce69acce3606ef',
    messagingSenderId: '889730267326',
    projectId: 'registration-e9e5b',
    authDomain: 'registration-e9e5b.firebaseapp.com',
    storageBucket: 'registration-e9e5b.appspot.com',
    measurementId: 'G-Q1NY6Z4RNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_oJ4tBk8mmo37PiRTNn54tfG13hvoi0',
    appId: '1:889730267326:android:c6cde522fb9561553606ef',
    messagingSenderId: '889730267326',
    projectId: 'registration-e9e5b',
    storageBucket: 'registration-e9e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpqFE0mdYPdZ2ReT3mPXdj_LHPghkOB-w',
    appId: '1:889730267326:ios:6c11f8638e50c1693606ef',
    messagingSenderId: '889730267326',
    projectId: 'registration-e9e5b',
    storageBucket: 'registration-e9e5b.appspot.com',
    iosBundleId: 'com.example.logging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpqFE0mdYPdZ2ReT3mPXdj_LHPghkOB-w',
    appId: '1:889730267326:ios:5a5927539cb5b9cb3606ef',
    messagingSenderId: '889730267326',
    projectId: 'registration-e9e5b',
    storageBucket: 'registration-e9e5b.appspot.com',
    iosBundleId: 'com.example.logging.RunnerTests',
  );
}
